ENGLISH = [
   "Do you have a map? I keep getting lost in your eyes 👀❤️‍🩹",
   "Are you a magician? Because whenever I look at you, everyone else disappears..",
   "Is your name Google? Because you have everything I've been searching for..",
   "Do you have a name, or can I call you mine?..",
   "Do you believe in love at first sight, or should I walk by again?..",
   "Do you have a Band-Aid? Because I just scraped my knee falling for you...",
   "Excuse me, but I think you dropped something: my jaw...",
   "Are you made of copper and tellurium? Because you're Cu-Te...",
   "If beauty were time, you'd be an eternity.",
   "Is there an airport nearby, or is that just my heart taking off?",
   "I must be a snowflake because I've fallen for you.",
   "I'm not a photographer, but I can definitely picture us together.",
   "If you were a vegetable, you'd be a cute-cumber!",
   "Can I follow you home? Cause my parents always told me to follow my dreams.",
   "Are you a camera? Because every time I look at you, I smile.",
   "Do you have a sunburn, or are you always this hot?",
   "Excuse me, but I think you owe me a drink. When I looked at you, I dropped mine.",
   "Is your name Wi-Fi? Because I'm feeling a connection.",
   "Are you a campfire? Because you're hot and I want s'more.",
   "I'm not a photographer, but I can picture you and me together.",
]
